runtime: python39

entrypoint: gunicorn -b :$PORT rekomendasi_by_product:app

service: capstone

handlers:
  - url: /static
    static_dir: static/

  - url: /.*  # Semua request lainnya akan diteruskan ke aplikasi Flask
    script: auto